In [1]:
import numpy as np   #alias -> np

In [ ]:
np.array([1, 2, 3])

array([1, 2, 3])

 Dimension and Shape of an array

In [ ]:
arr = np.array([1, 5, 7, 8])   #1D
arr.ndim

1

In [ ]:
arr = np.array(23)      #Scalar
arr.ndim

0

In [11]:
arr = np.array([[]])    #2D
arr.ndim

2

In [ ]:
arr = np.array([[[]]])    #3D
arr.ndim

3

in-built functions/properties

In [ ]:
#in-built functions/properties
#arange

range = np.arange(0,11)


In [14]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
range1 = np.arange(0,11, 4)  #start, end, step count/value

In [16]:
range1

array([0, 4, 8])

In [ ]:
#linspace -> evenly distribute values between assigned 2 values 

arr = np.linspace(0,1,5)  #start, stop, number of values
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
arr = np.linspace(0,1,10)  
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
arr = np.linspace(0,1,20)  
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
#logspace -> logarithmic scale array

arr = np.logspace(0, 1, 2) #starting power values, ending power value and points or values required 
arr

array([ 1., 10.])

In [21]:
arr = np.logspace(1, 3, 3)  #10^1, 10^3 .... 3 points
arr

array([  10.,  100., 1000.])

In [23]:
#np.zeros -> array full of zeros

arr = np.zeros(3)
arr

array([0., 0., 0.])

In [ ]:
arr = np.zeros(10)  #array of  size 10 zeros
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros([2, 3]) #matrix of 2 rows and 3 columns
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
arr = np.zeros([2, 3, 4, 5]) 
arr

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [30]:
#np.ones -> array of 1's

arr = np.ones(20)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [35]:
arr = np.ones([10,20])
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [36]:
arr = np.ones([10,20], dtype = int)
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [41]:
#np.full() ->create value of our choise

arr = np.full(2, 34)
arr

array([34, 34])

In [ ]:
arr = np.full(100, 333)  #no.of times, value
arr

array([333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333,
       333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333,
       333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333,
       333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333,
       333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333,
       333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333,
       333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333,
       333, 333, 333, 333, 333, 333, 333, 333, 333])

In [ ]:
arr = np.full([2,3], 10)  #matrix 2x3
arr

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
#np.empty ->uninitialzed array. it is used to create an array without setting any kind of values
#this method is used when u want to override values at latrer stages

arr = np.empty([2,3])
arr 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#np.random.rand() -> it generates random floats between(0,1) which are unifoemly distributed

arr = np. random.rand()
arr

0.8814414387670455

In [48]:
arr = np. random.rand(2)
arr

array([0.31309305, 0.82369636])

In [ ]:
arr = np.random.rand(2,3) #matrix
arr

array([[0.27851473, 0.96319393, 0.42549091],
       [0.8122561 , 0.41564156, 0.83918134]])

In [ ]:
#np.random.randn() -> random floates from standard normal distribution means mean is always zero and standard darivation is always 1

arr = np.random.randn(2)
arr

array([ 2.09355601, -2.43712339])

In [ ]:
arr = np.random.randn(2,4) #matrix
arr

array([[-0.70475534, -1.42642473,  1.04078897, -0.27998124],
       [-0.57987137,  0.2525485 , -3.0399627 ,  1.08086638]])

In [ ]:
#np.random.randint() -> generates random integer within paricular range

arr = np.random.randint(5)
arr

4

In [55]:
arr = np.random.randint(1,5)
arr

1

In [ ]:
arr = np.random.randint(1,5)     #start, end
arr

3

In [ ]:
arr = np.random.randint(1,5, size=[5,5])    #matrix
arr

array([[4, 2, 4, 2, 1],
       [1, 4, 1, 1, 4],
       [2, 4, 3, 1, 2],
       [1, 4, 3, 3, 1],
       [2, 2, 4, 2, 1]], dtype=int32)

Numpy Data Types & Type Casting

In [ ]:
arr = np.array([1,2,3,4.5,5.3]) 
arr

array([1. , 2. , 3. , 4.5, 5.3])

In [59]:
#numpy array do not allow to mutliple data to be stored in it

print(type(arr))

<class 'numpy.ndarray'>


In [60]:
lst = ["string", 1, 2, 3, 5.3]
arr = np.array(lst)
arr

array(['string', '1', '2', '3', '5.3'], dtype='<U32')

In [ ]:
""" 
datatypes                        Example

1. int32                          1,2,3
2. int64(default)               100, 2400
3. float32                      1.o, 3.14
4. float64(default)          1.00000000000002
5. bool                         True, False
6. complex                      1+2j, 3-4i
7. str                        "hello", "123"
"""

In [ ]:
arr = np.array([1,4,6,7,8,98,99,100])  #int
arr

array([  1,   4,   6,   7,   8,  98,  99, 100])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr = np.array([1,4,6.1,7,8,98,99,100])       #float
arr

array([  1. ,   4. ,   6.1,   7. ,   8. ,  98. ,  99. , 100. ])

In [64]:
arr.dtype

dtype('float64')

In [67]:
arr = np.array(["1",4,6,7,8,98,99,100])       #string
arr

array(['1', '4', '6', '7', '8', '98', '99', '100'], dtype='<U21')

In [68]:
arr.dtype

dtype('<U21')

In [ ]:
arr = np.array(["1",4,6,7,8,98,99,100], dtype= np.int32)       
arr

array([  1,   4,   6,   7,   8,  98,  99, 100], dtype=int32)

In [79]:
arr = np.array(["1",4,6,7,8,98,99,100], dtype= np.float32)       

In [80]:
arr.dtype

dtype('float32')

In [81]:
#typecasting  -> astype()

arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [82]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 2., 3.])

In [83]:
new_arr.dtype

dtype('float64')

In [84]:
new_arr = arr.astype(np.int64)
new_arr

array([1, 2, 3])

In [ ]:
#typecasting errors

""" 

arr = np.array(["1", "2", "hey"])
arr2 = arr.astype(np.int32)
arr2

"""

ValueError: invalid literal for int() with base 10: np.str_('hey')