In [202]:
import numpy as np   #alias -> np

In [203]:
np.array([1, 2, 3])

array([1, 2, 3])

 Dimension and Shape of an array

In [204]:
arr = np.array([1, 5, 7, 8])   #1D
arr.ndim

1

In [205]:
arr = np.array(23)      #Scalar
arr.ndim

0

In [206]:
arr = np.array([[]])    #2D
arr.ndim

2

In [207]:
arr = np.array([[[]]])    #3D
arr.ndim

3

in-built functions/properties

In [208]:
#in-built functions/properties
#arange

range = np.arange(0,11)


In [209]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [210]:
range1 = np.arange(0,11, 4)  #start, end, step count/value

In [211]:
range1

array([0, 4, 8])

In [212]:
#linspace -> evenly distribute values between assigned 2 values 

arr = np.linspace(0,1,5)  #start, stop, number of values
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [213]:
arr = np.linspace(0,1,10)  
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [214]:
arr = np.linspace(0,1,20)  
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [215]:
#logspace -> logarithmic scale array

arr = np.logspace(0, 1, 2) #starting power values, ending power value and points or values required 
arr

array([ 1., 10.])

In [216]:
arr = np.logspace(1, 3, 3)  #10^1, 10^3 .... 3 points
arr

array([  10.,  100., 1000.])

In [217]:
#np.zeros -> array full of zeros

arr = np.zeros(3)
arr

array([0., 0., 0.])

In [218]:
arr = np.zeros(10)  #array of  size 10 zeros
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [219]:
arr = np.zeros([2, 3]) #matrix of 2 rows and 3 columns
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [220]:
arr = np.zeros([2, 3, 4, 5]) 
arr

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [221]:
#np.ones -> array of 1's

arr = np.ones(20)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [222]:
arr = np.ones([10,20])
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [223]:
arr = np.ones([10,20], dtype = int)
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [224]:
#np.full() ->create value of our choise

arr = np.full(2, 34)
arr

array([34, 34])

In [225]:
arr = np.full(100, 333)  #no.of times, value
arr

array([333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333,
       333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333,
       333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333,
       333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333,
       333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333,
       333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333,
       333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333, 333,
       333, 333, 333, 333, 333, 333, 333, 333, 333])

In [226]:
arr = np.full([2,3], 10)  #matrix 2x3
arr

array([[10, 10, 10],
       [10, 10, 10]])

In [227]:
#np.empty ->uninitialzed array. it is used to create an array without setting any kind of values
#this method is used when u want to override values at latrer stages

arr = np.empty([2,3])
arr 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [228]:
#np.random.rand() -> it generates random floats between(0,1) which are unifoemly distributed

arr = np. random.rand()
arr

0.9830352194641463

In [229]:
arr = np. random.rand(2)
arr

array([0.27194686, 0.72262922])

In [230]:
arr = np.random.rand(2,3) #matrix
arr

array([[0.26062059, 0.64667157, 0.32052937],
       [0.69327772, 0.64317215, 0.8359249 ]])

In [231]:
#np.random.randn() -> random floates from standard normal distribution means mean is always zero and standard darivation is always 1

arr = np.random.randn(2)
arr

array([-0.48681237,  0.9406341 ])

In [232]:
arr = np.random.randn(2,4) #matrix
arr

array([[-0.38108985, -1.12879036, -0.0766915 ,  0.42712019],
       [-0.32256728, -1.92835858, -1.29378143,  0.90731993]])

In [233]:
#np.random.randint() -> generates random integer within paricular range

arr = np.random.randint(5)
arr

2

In [234]:
arr = np.random.randint(1,5)
arr

1

In [235]:
arr = np.random.randint(1,5)     #start, end
arr

3

In [236]:
arr = np.random.randint(1,5, size=[5,5])    #matrix
arr

array([[4, 3, 3, 2, 2],
       [3, 3, 2, 3, 2],
       [1, 4, 2, 4, 2],
       [4, 3, 2, 2, 1],
       [4, 3, 1, 4, 2]], dtype=int32)

Numpy Data Types & Type Casting

In [237]:
arr = np.array([1,2,3,4.5,5.3]) 
arr

array([1. , 2. , 3. , 4.5, 5.3])

In [238]:
#numpy array do not allow to mutliple data to be stored in it

print(type(arr))

<class 'numpy.ndarray'>


In [239]:
lst = ["string", 1, 2, 3, 5.3]
arr = np.array(lst)
arr

array(['string', '1', '2', '3', '5.3'], dtype='<U32')

In [240]:
""" 
datatypes                        Example

1. int32                          1,2,3
2. int64(default)               100, 2400
3. float32                      1.o, 3.14
4. float64(default)          1.00000000000002
5. bool                         True, False
6. complex                      1+2j, 3-4i
7. str                        "hello", "123"
"""

' \ndatatypes                        Example\n\n1. int32                          1,2,3\n2. int64(default)               100, 2400\n3. float32                      1.o, 3.14\n4. float64(default)          1.00000000000002\n5. bool                         True, False\n6. complex                      1+2j, 3-4i\n7. str                        "hello", "123"\n'

In [241]:
arr = np.array([1,4,6,7,8,98,99,100])  #int
arr

array([  1,   4,   6,   7,   8,  98,  99, 100])

In [242]:
arr.dtype

dtype('int64')

In [243]:
arr = np.array([1,4,6.1,7,8,98,99,100])       #float
arr

array([  1. ,   4. ,   6.1,   7. ,   8. ,  98. ,  99. , 100. ])

In [244]:
arr.dtype

dtype('float64')

In [245]:
arr = np.array(["1",4,6,7,8,98,99,100])       #string
arr

array(['1', '4', '6', '7', '8', '98', '99', '100'], dtype='<U21')

In [246]:
arr.dtype

dtype('<U21')

In [247]:
arr = np.array(["1",4,6,7,8,98,99,100], dtype= np.int32)       
arr

array([  1,   4,   6,   7,   8,  98,  99, 100], dtype=int32)

In [248]:
arr = np.array(["1",4,6,7,8,98,99,100], dtype= np.float32)       

In [249]:
arr.dtype

dtype('float32')

In [250]:
#typecasting  -> astype()

arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [251]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 2., 3.])

In [252]:
new_arr.dtype

dtype('float64')

In [253]:
new_arr = arr.astype(np.int64)
new_arr

array([1, 2, 3])

In [254]:
#typecasting errors

""" 

arr = np.array(["1", "2", "hey"])
arr2 = arr.astype(np.int32)
arr2

"""

' \n\narr = np.array(["1", "2", "hey"])\narr2 = arr.astype(np.int32)\narr2\n\n'

In [255]:
#creating multidimentional arrray manually

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

In [256]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [257]:
arr.ndim

2

In [258]:
arr.shape

(2, 3)

In [259]:
arr.size

6

In [260]:
arr.itemsize

8

Array Reshaping -> Reshape, Ravel, flatten

In [261]:
# Reshape

arr = np.array([1, 2, 3, 4, 5, 6])    #1D
reshaped = arr.reshape(2,3)          # to matrix
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [262]:
reshape2 = reshaped.reshape(3,2)

In [263]:
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [264]:
#ravel -> convet 1D array  : it changes the array 

ravel = reshape2.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [265]:
ravel[0] = 100
print(ravel)
print(reshape2)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


In [266]:
# flatten -> to 1D array    : instead of changing existing array it makes copy of array and perform operations

flat = reshape2.flatten()
flat

array([100,   2,   3,   4,   5,   6])

In [267]:
flat[0] = 1

In [268]:
flat   

array([1, 2, 3, 4, 5, 6])

In [269]:
reshape2   # as u can see here it makes copy and do not change existinf array

array([[100,   2],
       [  3,   4],
       [  5,   6]])

Arithmetic Operations on Arrays

In [270]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [271]:
# addition:

print(a+b)

[5 7 9]


In [272]:
# subtration:

print(a-b)

[-3 -3 -3]


In [273]:
# multiplication:

print(a*b)

[ 4 10 18]


In [274]:
# division:

print(a/b)

[0.25 0.4  0.5 ]


In [275]:
# integer division:

print(b//a)

[4 2 2]


In [276]:
#modulus(remainder):

print(b%a)

[0 1 0]


In [277]:
# exponent(power):

print(a**2)
print(b**2)

[1 4 9]
[16 25 36]


Universal Functions -> ufuncs

In [278]:
arr = np.array([1, 4, 9, 16])

In [279]:
# square root -> np.sqrt

print(np.sqrt(arr))

[1. 2. 3. 4.]


In [280]:
# exponentioal -> np.exp -> e^x -> x is any integer

print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [281]:
#sine function -> np.sin

angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


Indexing and Slicing 

In [282]:
a = [1, 2, 3, 4, 5]

In [283]:
a[-1:-4:-1]  #[start:stop:step]

[5, 4, 3]

In [284]:
a[: :2]  #indexes = 0, 2, 4

[1, 3, 5]

In [285]:
#positive indexing

arr = np.array([10, 20, 30, 40, 50])
#indexes = 0, 2, 4
arr[::2]

array([10, 30, 50])

In [286]:
#negative indexing
print(arr[-1])

50


In [287]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [288]:
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]


In [289]:
print(matrix[1: , 1:])

[[5 6]
 [8 9]]


In [290]:
#np.take -> built in function to perform indexing and slicing

arr = np.array([10,20,30,40,50])
ind = [0, 2]
print(np.take(arr, ind))

[10 30]


In [291]:
#Ierating with nditer()

arr = np.array([[1,2], [3,4]])

In [292]:
for x in np.nditer(arr):
    print(x, end = " ")

1 2 3 4 

In [293]:
#ndenumerate() -> both index + value

for ind, x in np.ndenumerate(arr):
    print(ind, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [294]:
# views vs copies 
# view shows partucular data and as per requirement update it 

arr = np.array([1,2,3,4,5])
view = arr[1:3]    # shows partucular data 
view

array([2, 3])

In [295]:
view[0] = 200   # assign data

In [296]:
view

array([200,   3])

In [297]:
arr

array([  1, 200,   3,   4,   5])

In [298]:
# copy : it shows partucular data and but do not update it

copy = arr[1:3].copy()
copy

array([200,   3])

In [299]:
copy[0] = 2
copy

array([2, 3])

In [300]:
arr

array([  1, 200,   3,   4,   5])

In [301]:
#transpose

arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [302]:
print(arr.transpose())

[[1 3]
 [2 4]]


In [303]:
#Swapaxes -> swap 2 specific axes in a matrix

arr = np.array([[[1,2], [3,4]]])
arr.shape

(1, 2, 2)

In [304]:
swap = np.swapaxes(arr,0 ,2)
swap.shape

(2, 2, 1)

In [305]:
# concatenation:

a = np.array([1,3])
b = np.array([2,4])

In [306]:
c = np.concatenate((a,b))
c

array([1, 3, 2, 4])

In [307]:
print(c)

[1 3 2 4]


In [308]:
#np.vstack(), hstack(), stack()

arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

In [309]:
print(np.vstack((arr1,arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [310]:
print(np.hstack((arr1,arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [311]:
print(np.stack((arr1,arr2)))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [312]:
print(np.stack((arr1,arr2), axis = 2))  #changes axis 

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


Splitting Arrays

In [313]:
arr1 = np.array([[1,2], [3,4], [5,6], [7,8]])

In [314]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [315]:
print(np.split(arr1, 2))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [316]:
print(np.split(arr1, 4))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


Repeating

In [317]:
arr = np.array([1, 2, 3])
print(np.repeat(arr, 2))

[1 1 2 2 3 3]


In [318]:
print(np.repeat(arr, 3))

[1 1 1 2 2 2 3 3 3]


In [319]:
print(np.repeat(arr, 5))

[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3]


In [320]:
print(np.repeat(arr, 12))

[1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3]


In [321]:
#tile -> repeat whole array sequencillay once 

print(np.tile(arr, 2))


[1 2 3 1 2 3]


In [322]:

print(np.tile(arr, 3))

[1 2 3 1 2 3 1 2 3]


In [323]:

print(np.tile(arr, 5))

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


In [324]:

print(np.tile(arr, 12))

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


Aggregate Functions:

In [325]:
#sum

arr = np.array([1, 2, 3])
print(np.sum(arr))        

6


In [326]:
#mean

arr = np.array([1, 2, 3])
print(np.mean(arr)) 

2.0


In [327]:
#median

arr = np.array([1, 2, 3])
print(np.median(arr)) 

2.0


In [328]:
#standard daviation(std)

arr = np.array([1, 2, 3])
print(np.std(arr)) 

0.816496580927726


In [329]:
#variance

arr = np.array([1, 2, 3])
print(np.var(arr)) 

0.6666666666666666


In [330]:
#max

arr = np.array([1, 2, 3])
print(np.max(arr)) 

3


In [331]:
#min

arr = np.array([1, 2, 3])
print(np.min(arr)) 

1


In [332]:
#matrix

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [333]:
print(np.sum(matrix, axis = 0))

[12 15 18]


In [334]:
print(np.sum(matrix, axis = 1))

[ 6 15 24]


In [335]:
# Cumulative Operations -> running total

arr

array([1, 2, 3])

In [336]:
print(np.cumsum(arr))

[1 3 6]


In [337]:
print(np.cumprod(arr))

[1 2 6]


Conditional Based Choises

In [338]:
#where

arr

array([1, 2, 3])

In [339]:
result = np.where(arr <2, "low", "high")

In [340]:
result

array(['low', 'high', 'high'], dtype='<U4')

In [341]:
arr

array([1, 2, 3])

In [342]:
# argwhere -> row column positions for 2d arrays

arr

array([1, 2, 3])

In [343]:
print(np.argwhere(arr))

[[0]
 [1]
 [2]]


In [344]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [345]:
print(np.argwhere(matrix))

[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]


In [346]:
print(np.argwhere(matrix > 5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [347]:
# Logical and:

arr

array([1, 2, 3])

In [348]:
mask = np.logical_and(arr > 3, arr < 6)

In [349]:
arr[mask]

array([], dtype=int64)

In [350]:
# Logical or:

mask = np.logical_or(arr > 3, arr < 6)

In [351]:
arr[mask]

array([1, 2, 3])

In [352]:
mask = np.logical_not(arr > 3, arr < 6)

In [353]:
arr[mask]

array([1, 2, 3])

In [354]:
mask = np.logical_xor(arr > 3, arr < 6)

In [355]:
arr[mask]

array([1, 2, 3])

In [356]:
# nonzero

arr2 = np.array([0, 1, 5, 0, 5])
arr2

array([0, 1, 5, 0, 5])

In [357]:
print(np.nonzero(arr2))

(array([1, 2, 4]),)


In [358]:
#Brodcasting

image = np.array([[200, 150], [100, 250]])
image.shape

(2, 2)

In [359]:
brightness = image + 50
brightness

array([[250, 200],
       [150, 300]])

In [360]:
# Vectorization:

# np.vectorize() -> convert a regular function to be applied on an array.


def square(x):
    return x*x

vfunc = np.vectorize(square)

In [361]:
arr

array([1, 2, 3])

In [362]:
print(vfunc(arr))

[1 4 9]


In [363]:
# dealing with missing values:

# np.nan -> not a number.

In [364]:
a = np.array([1, 2 , np.nan, 4])

In [365]:
a

array([ 1.,  2., nan,  4.])

In [366]:
# np.inf and -np.inf -> positive and negative infinites


# np.isnan
# np.isinf
# np.isfinite 
# these functions used to detect null, infinite and finite values

In [367]:
a

array([ 1.,  2., nan,  4.])

In [368]:
# np.isnan

print(np.isnan(a))

[False False  True False]


In [369]:
# np.isinf

b = np.array([1, np.nan, np.inf, 10.2, 40])

In [370]:
print(np.isinf(b))

[False False  True False False]


In [371]:
# remove Nan/ infinite values

new_b = np.nan_to_num(b)

In [372]:
new_b

array([1.00000000e+000, 0.00000000e+000, 1.79769313e+308, 1.02000000e+001,
       4.00000000e+001])